name: 构建 ARM32 二进制文件

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-arm32:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v2

      - name: 安装交叉编译工具链
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: 设置 Rust 交叉编译环境
        run: |
          rustup target add armv7-unknown-linux-gnueabihf
          mkdir -p ~/.cargo
          echo "[target.armv7-unknown-linux-gnueabihf]" >> ~/.cargo/config
          echo "linker = 'arm-linux-gnueabihf-gcc'" >> ~/.cargo/config

      - name: 缓存依赖项
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: 构建 ARM32 发布版本
        run: cargo build --release --target armv7-unknown-linux-gnueabihf

      - name: 打包二进制文件
        run: tar cfz htmlq-armv7-linux.tar.gz -C target/armv7-unknown-linux-gnueabihf/release .

      - name: 发布到 GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: htmlq-armv7-linux.tar.gz
